import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.Map;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'robertkuhar' at '8/14/16 5:37 PM' with Gradle 2.14.1
 *
 * @author robertkuhar, @date 8/14/16 5:37 PM
 */
public class Library {
    private static final Logger LOGGER = LoggerFactory.getLogger(Library.class);

    public boolean someLibraryMethod() {
        LOGGER.trace("someLibraryMethod()");
        return true;
    }

    public String someLibraryMethodReturningString(){
        final GsonBuilder builder = new GsonBuilder();
        final Gson gson = builder.create();
        final Map<Integer, String> values = new HashMap<Integer, String>();
        values.put(1, "val1");
        values.put(2, "val2");
        values.put(3, "val3");
        return gson.toJson(values);
    }
}
